### ISSUE TITLE
All beacon activity missing!

### ISSUE THREAD

**Issue by johnlev** [RadiusNetworks/proximitykit-ios#11]
I have at this point written a number of apps using this wonderful framework. All of a sudden though (I'm not sure when, but about a month ago) all beacon activity was no longer registered at all by this framework! NOT EVEN IN MY PUBLISHED APPLICATIONS (which had been working swimmingly before hand)! This was an effect I observed on all platforms, iPhone X, iPhone 8, iPhone 5s, etc. I have yet to test on a device with an outdated iOS, so an upgrade may be the problem. It is important that I get this back up and running. So far I have been very content with this library, but if I have to I might have to abandon it to do the beacon tracking myself, which I would rather not do.

Let me know if there is something I can do to help track down this problem

**Comment by johnlev** [comment]
I'm also posting here to see if anyone is experiencing the same problems that I am

**Comment by csexton** [comment]
@johnlev can you contact support at https://goo.gl/vMDpGG with details on your kit (the kit url from the config would be all we need to look it up).
