### ISSUE TITLE
Freezes when no internet connection is available

### ISSUE THREAD

**Issue by barksten** [RadiusNetworks/proximitykit-ios#5]
Using the 1.0.5 preview without an internet connection will freeze the SDK with 100% CPU usage for some time.
The log says:
> ProximityKit[Error] API Request Failed with Error: Error Domain=NSURLErrorDomain Code=-1009 "Internetanslutningen verkar vara nedkopplad." UserInfo=0x1bc3ec10 {NSErrorFailingURLStringKey=http://proximitykit.radiusnetworks.com/api/kits/XXXX, NSErrorFailingURLKey=http://proximitykit.radiusnetworks.com/api/kits/XXXX, NSLocalizedDescription=Internetanslutningen verkar vara nedkopplad., NSUnderlyingError=0x1bd7e460 "Internetanslutningen verkar vara nedkopplad."}

(XXXX is censured)

**Comment by csexton** [comment]
That is strange, especially the 100% CPU. I attempted to reproduce here by putting my phone in airplane mode and launching a test app.

One thing to try is setting up the `didFailWithError` callback. This way we can see if we are getting an error from the framework. 

```objective-c
- (void)proximityKit:(RPKManager *)manager didFailWithError:(NSError *)error {
 NSLog(@"Error: %@", [error debugDescription]);
}
```

When I run with that I see the following (with a few line breaks added to make it readable):

```
2015-01-28 15:47:21.868 Nearby[15337:7263532] Error: 
  Error Domain=NSURLErrorDomain 
  Code=-1009 "The Internet connection appears to be offline." 
  UserInfo=0x1740e7c80 {
    NSUnderlyingError=0x170249540 "The Internet connection appears to be offline.",
    NSErrorFailingURLStringKey=http://proximitykit.radiusnetworks.com/api/kits/X,
    NSErrorFailingURLKey=http://proximitykit.radiusnetworks.com/api/kits/X,
    _kCFStreamErrorDomainKey=12,
    _kCFStreamErrorCodeKey=8,
   NSLocalizedDescription=The Internet connection appears to be offline.
```

**Comment by barksten** [comment]
I started the kit without a delegate (by passing nil). Maybe that will contribute to the stall?
Hopefully I will have more time to investigate it further tomorrow..

**Comment by csexton** [comment]
Having a nil delegate shouldn't effect behavior (other than never calling a selector), but I will test that way locally and see. Curious what you see in the error callback.

How do you force the phone to have no internet? I am just using airplane mode, but I was wondering if there is a better way to reproduce your conditions here.

**Comment by barksten** [comment]
I've profiled with instruments and it looks like its a problem related to a formatter.
[RPKAnalytics formatdate:]
It looks like the formatter is not cached (in a static var). Formatters are generally very expensive to allocate so i guess that might by the problem.

**Comment by csexton** [comment]
Thanks for the info, the trace was particularly helpful. I have made a minor optimization to the JSON creation and ran a release. Mind giving v1.0.7 a try?

https://github.com/RadiusNetworks/proximitykit-ios/releases/tag/v1.0.7

**Comment by csexton** [comment]
I believe this was resolved in v1.0.7, if you have any problems feel free to re-open.

**Comment by alvincrisuy** [comment]
It was working yesterday. But now it gives an error in version 1.2.3 and in 1.2.5

The device has an internet connection.

Log: 

> 2016-04-13 22:53:33.116 KWTG-iOS[207:5401] 
ProximityKit[Error] API Request Failed with Error: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSErrorFailingURLStringKey=https://proximitykit.radiusnetworks.com/api/kits/XXXX, _kCFStreamErrorCodeKey=50, NSErrorFailingURLKey=https://proximitykit.radiusnetworks.com/api/kits/XXXX, NSLocalizedDescription=The Internet connection appears to be offline., _kCFStreamErrorDomainKey=1, NSUnderlyingError=0x160906e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50}}}

**Comment by csexton** [comment]
@alvincrisuy Sorry about that. Can you email support@radiusnetworks.com with details of your kit config, and we will take a look to see what is causing the error.
