### ISSUE TITLE
tutorial: Undefined symbols for architecture arm64: _OBJC_CLASS_$_CBPeripheralManager

### ISSUE THREAD

**Issue by gamecubate** [RadiusNetworks/proximitykit-ios#7]
Per your [Proximity Kit tutorial](https://proximitykit.radiusnetworks.com/docs/ios/getting-started) . Tested on OSX 10.11.5, running xcode 7.3.1, targeting iOS 9.3 device.

I am unable to build test app. Followed instructions to best of my abilities (videos and tutorials are out of date). Ultimately, build fails with this mention:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CBPeripheralManager", referenced from:
      objc-class-ref in ProximityKit(ProximityKit-arm64-master.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by csexton** [comment]
Sorry about that @gamecubate, we have just started an effort to refresh the documentation. 

I believe that error is indicating the need to link against CoreBluetooth. You can do this in the project settings under `General->Linked Frameworks and Libraries`. Click on the `+` and search for "CoreBluetooth.framework".

**Comment by gamecubate** [comment]
Thanks. One problem solved. Will open other issues for... other issues related to the Proximity Kit tutorial. Is this OK? As for this issue, should I leave it opened for you to later close?

**Comment by csexton** [comment]
Thanks @gamecubate, I am going to open a new issue in the documentation repo for this.
