### ISSUE TITLE
tutorial: managerWithDelegate: is deprecated. use managerWithDelegate:andConfig: instead.

### ISSUE THREAD

**Issue by gamecubate** [RadiusNetworks/proximitykit-ios#9]
Per your [Proximity Kit tutorial](https://proximitykit.radiusnetworks.com/docs/ios/getting-started) . Tested on OSX 10.11.5, running xcode 7.3.1, targeting iOS 9.3 device.

AppDelegate.m:
```
...
self.proximityKitManager = [RPKManager managerWithDelegate:self];
...
```

This results in a warning: "managerWithDelegate:" is deprecated. Use "managerWithDelegate:andConfig:" instead.

An updated call will help.

**Comment by csexton** [comment]
Merged into https://github.com/RadiusNetworks/proximitykit-documentation/issues/24

Thanks @gamecubate.
